---
title: Akshat Kedia | Web Developer
timezone: Asia/Kolkata
collections:
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    link:
email: akshat.kedia@outlook.com
description: Personal website of Akshat Kedia, student at Launchschool and freelance
  web developer.
permalink: pretty
url: https://akshatkedia.github.io/
twitter_username: _akshatkedia
github_username: akshatkedia
markdown: kramdown
theme: minima
twitter:
  username: _akshatkedia
