---
title: Akshat Kedia
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    link: 
plugins:
- jekyll-seo-tag
- jekyll-sitemap
email: akshat.kedia@outlook.com
description: Personal website of Akshat Kedia, student at Launchschool and freelance
  web developer.
permalink: pretty
url: https://akshatkedia.github.io/
twitter_username: _akshatkedia
github_username: akshatkedia
markdown: kramdown
theme: minima
twitter:
  username: _akshatkedia
