---
title: Akshat Kedia's Webspace
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: akshat.kedia@outlook.com
description: 'A blog by Akshat Kedia.

'
baseurl: 
url: http://yourdomain.com
twitter_username: _akshatkedia
github_username: akshatkedia
markdown: kramdown
