---
title: Akshat Kedia | Web Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: akshat.kedia@outlook.com
description: 'Personal website of Akshat Kedia, student at Launchschool and freelance
  web developer.

'
baseurl: ''
url: akshatkedia.github.io
twitter_username: _akshatkedia
github_username: akshatkedia
author: Akshat Kedia
twitter:
  username: _akshatkedia
markdown: kramdown
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
