---
---

---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
- type: text
  name: link
  label: Link
pages:
- _projects/papa-pawsome.md
- _projects/indian-food-lovers-barcelona.md
