---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: text
  name: link
  label: Link
pages:
- _projects/the-thumbprints.md
- _projects/papa-pawsome.md
- _projects/indiaspend.md
- _projects/indian-food-lovers-barcelona.md
- _projects/gauri-arora.md
- _projects/maker-s-asylum-membership-portal.md
- _projects/leefe.md
- _projects/mystic-ved.md
